#!/usr/bin/env bash
# libs/require.sh — shared dependency and utility functions
# Source this from any script: source "$(dirname "$0")/../libs/require.sh"

set -euo pipefail

# ── Colors (only if terminal) ────────────────────────────────────────────────

if [[ -t 2 ]]; then
  _RED=$'\033[0;31m'  _GREEN=$'\033[0;32m'  _YELLOW=$'\033[0;33m'
  _CYAN=$'\033[0;36m' _BOLD=$'\033[1m'      _RESET=$'\033[0m'
else
  _RED="" _GREEN="" _YELLOW="" _CYAN="" _BOLD="" _RESET=""
fi

# ── Logging ──────────────────────────────────────────────────────────────────

log_info()  { echo -e "${_CYAN}info:${_RESET} $*" >&2; }
log_ok()    { echo -e "${_GREEN}  ok:${_RESET} $*" >&2; }
log_warn()  { echo -e "${_YELLOW}warn:${_RESET} $*" >&2; }
log_error() { echo -e "${_RED}error:${_RESET} $*" >&2; }
log_fatal() { echo -e "${_RED}fatal:${_RESET} $*" >&2; exit 1; }

# ── Dependency checking ──────────────────────────────────────────────────────

require() {
  local missing=()
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
  done
  if [[ ${#missing[@]} -gt 0 ]]; then
    log_error "missing required commands: ${_BOLD}${missing[*]}${_RESET}"
    exit 1
  fi
}

require_any() {
  for cmd in "$@"; do
    if command -v "$cmd" >/dev/null 2>&1; then
      echo "$cmd"
      return 0
    fi
  done
  return 1
}

# ── Project path resolution ──────────────────────────────────────────────────

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DIR_CONFIG="${PROJECT_ROOT}/config"
DIR_KEYS="${PROJECT_ROOT}/keys"
DIR_CACHE="${PROJECT_ROOT}/cache"
DIR_IMAGES="${PROJECT_ROOT}/images"
DIR_LIBS="${PROJECT_ROOT}/libs"
DIR_SECRETS="${PROJECT_ROOT}/secrets"
DIR_TEMPLATES="${PROJECT_ROOT}/templates"
DIR_PATCHED="${PROJECT_ROOT}/images/patched"

# ── Config loading ───────────────────────────────────────────────────────────

load_config() {
  local board="$1"
  local defaults="${DIR_CONFIG}/defaults.env"
  local board_cfg="${DIR_CONFIG}/boards/${board}.env"

  [[ -f "$defaults" ]]  || log_fatal "defaults config not found: $defaults"
  [[ -f "$board_cfg" ]] || log_fatal "board config not found: $board_cfg"

  # shellcheck source=/dev/null
  source "$defaults"
  # shellcheck source=/dev/null
  source "$board_cfg"

  local required_vars=(ARMBIAN_BOARD_SLUG ARMBIAN_DISTRO ARMBIAN_BRANCH ARMBIAN_VARIANT)
  for var in "${required_vars[@]}"; do
    if [[ -z "${!var+x}" ]]; then
      log_fatal "required variable ${_BOLD}${var}${_RESET} is not set (check defaults.env and boards/${board}.env)"
    fi
  done
}

# ── Lock file helpers ────────────────────────────────────────────────────────

write_lock() {
  local dir="$1"; shift
  local lockfile="${dir}/.pull-lock"
  {
    echo "# .pull-lock (auto-generated by pull-image.sh — do not edit)"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    for kv in "$@"; do
      echo "$kv"
    done
  } > "$lockfile"
}

read_lock() {
  local lockfile="${1}/.pull-lock"
  if [[ -f "$lockfile" ]]; then
    # shellcheck source=/dev/null
    source "$lockfile"
    return 0
  fi
  return 1
}
